services:
  mysql:
    image: mysql:8.0
    container_name: craftopia-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: craftopia_db
      MYSQL_USER: craftopia
      MYSQL_PASSWORD: craftopia123
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: craftopia-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      PORT: 5000
      DB_HOST: mysql
      DB_USER: craftopia
      DB_PASSWORD: craftopia123
      DB_NAME: craftopia_db
      DB_PORT: 3306

  frontend:
    build: ./frontend
    container_name: craftopia-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

volumes:
  mysql_data:
